apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt-deployment
spec:
  replicas: 1  # You can adjust this based on how many instances you want to run
  selector:
    matchLabels:
      app: dbt
  template:
    metadata:
      labels:
        app: dbt
    spec:
      containers:
        - name: dbt
          image: naushc/dbt-snowflake:latest  # Replace with your pre-built image
          command: ["dbt", "run"]
          envFrom:
            - secretRef:
                name: dbt-profiles  # Reference the secret for DBT profiles
