name: CI/CD Pipeline for DBT to Kubernetes

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t dbt-snowflake .

    # Push Docker Image to Docker Hub (optional step)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag dbt-snowflake:latest naushc/dbt-snowflake:latest
        docker push naushc/dbt-snowflake:latest

    # Set up Kubernetes config
    - name: Set up KUBECONFIG
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBECONFIG" > ~/.kube/config
        kubectl get nodes  # Test if the cluster is accessible
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

    # Deploy to Kubernetes Cluster
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/dbt-deployment.yaml  # Make sure to create a proper Kubernetes manifest

    # Run dbt command in the container
    - name: Run dbt
      run: |
        kubectl run dbt-job --image=yourdockerhubusername/dbt-snowflake:latest --restart=Never --command -- dbt run
