WITH raw_data AS (
    SELECT
        SYMBOL,
        TIMESTAMP,
        CAST(OPEN AS FLOAT) AS OPEN_PRICE,
        CAST(HIGH AS FLOAT) AS HIGH_PRICE,
        CAST(LOW AS FLOAT) AS LOW_PRICE,
        CAST(CLOSE AS FLOAT) AS CLOSE_PRICE,
        CAST(VOLUME AS NUMBER(19,0)) AS VOLUME,
        CAST(DIVIDENDS AS FLOAT) AS DIVIDENDS,
        STOCKSPLITS,
        RECORD_METADATA
    FROM {{ source('raw', 'stock_prices_all') }}
),

calculated_measures AS (
    SELECT
        SYMBOL,
        TIMESTAMP,
        NULL as 'dateasof',
        OPEN_PRICE,
        HIGH_PRICE,
        LOW_PRICE,
        CLOSE_PRICE,
        VOLUME,
        DIVIDENDS,
        STOCKSPLITS,

        -- Daily Price Range
        HIGH_PRICE - LOW_PRICE AS DAILY_PRICE_RANGE,

        -- Daily Percentage Change
        ((CLOSE_PRICE - OPEN_PRICE) / NULLIF(OPEN_PRICE, 0)) * 100 AS DAILY_PERCENT_CHANGE,

        -- Rolling Averages
        AVG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TIMESTAMP ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AVG_CLOSE_7D,
        AVG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TIMESTAMP ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS AVG_CLOSE_30D,

        -- Max-Min Spread
        MAX(CLOSE_PRICE) OVER (PARTITION BY SYMBOL) - MIN(CLOSE_PRICE) OVER (PARTITION BY SYMBOL) AS MAX_MIN_SPREAD,

        -- Total Dividends
        SUM(DIVIDENDS) OVER (PARTITION BY SYMBOL) AS TOTAL_DIVIDENDS,

        -- Count of Stock Splits
        COUNT(DISTINCT STOCKSPLITS) OVER (PARTITION BY SYMBOL) AS STOCK_SPLIT_COUNT
    FROM raw_data
)

SELECT * FROM calculated_measures
